//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8762
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.8762 版自动生成。
// 
namespace PDA_WMSClient.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WMS_WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WMS_WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WMS_WebService() {
            this.Url = "http://192.168.19.92:8990/WMS_WebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrtStoreInfomation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GrtStoreInfomation(string code, out decimal num) {
            object[] results = this.Invoke("GrtStoreInfomation", new object[] {
                        code});
            num = ((decimal)(results[1]));
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGrtStoreInfomation(string code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GrtStoreInfomation", new object[] {
                        code}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGrtStoreInfomation(System.IAsyncResult asyncResult, out decimal num) {
            object[] results = this.EndInvoke(asyncResult);
            num = ((decimal)(results[1]));
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InStorage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InStorage(string code, string storeInfo, string virifycode, decimal count, int num) {
            object[] results = this.Invoke("InStorage", new object[] {
                        code,
                        storeInfo,
                        virifycode,
                        count,
                        num});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInStorage(string code, string storeInfo, string virifycode, decimal count, int num, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InStorage", new object[] {
                        code,
                        storeInfo,
                        virifycode,
                        count,
                        num}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInStorage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
